### PR TITLE
changed StoreService to InstanceService to fix getShopwareVersion error

### PR DESCRIPTION
**Pull request by Necriso**
## Summary
getShopwareVersion method is not located in StoreService anymore.
To get this plugin to work again changed StoreService class to InstanceService Class

**Fixed issue**:  #231

### CODE REVIEW

**Comment by peterojo** [comment]
Hi @Necriso thanks for the contribution, we will test this and review it ASAP

**Comment by Morerice** [comment]
Hi @Necriso,

Thanks for opening this PR. Unfortunately this solution would break compatibility with some Shopware 6 versions, since the InstanceService was only introduced in [v6.4.4.0](https://github.com/shopware/platform/blob/v6.4.4.0/src/Core/Framework/Store/Services/InstanceService.php).

Instead of injecting this service, could you inject the version directly as an argument of the service? (Something like `<argument>%kernel.shopware_version%</argument>` should do the trick)

Thanks,
Jean
Adyen

**Comment by wwnorden** [comment]
Hello @Morerice,

thanks for your reply. We can fix it on our own but first its not safe for further updates and second does it mean, that the current version of adyen plugin is not supporting the latest Shopware release?! Sounds a bit weird but we are sure you will fix it asap or don`t you?

Thanks in advanced

**Comment by Morerice** [comment]
Hi @wwnorden 

Yes we will fix it asap. However, since @Necriso opened the PR initially we wanted to give him a day or two to see if he wanted to change this PR and implement the fix we suggested. If no response will be given we will update it ourselves.

Alternatively, if you agree with my previous suggestion, you could also open a PR to be reviewed and released by us, with the proposed solution.

Best regards,
Jean
Adyen

**Comment by Morerice** [comment]
> Hi @Necriso,
> 
> Thanks for opening this PR. Unfortunately this solution would break compatibility with some Shopware 6 versions, since the InstanceService was only introduced in [v6.4.4.0](https://github.com/shopware/platform/blob/v6.4.4.0/src/Core/Framework/Store/Services/InstanceService.php).
> 
> Instead of injecting this service, could you inject the version directly as an argument of the service? (Something like `<argument>%kernel.shopware_version%</argument>` should do the trick)
> 
> Thanks, Jean Adyen

PR #234 with this solution has been merged and released.

**Pull request closed without merging**
